In [1]:
# importing the numpy package
import numpy as np

### 1. Create a 3x3x3 array with random values

In [2]:
x = np.random.random((3,3,3))
print(x)

[[[0.01540905 0.15164631 0.83107088]
  [0.36165862 0.56949454 0.62783475]
  [0.88472212 0.41594101 0.19775282]]

 [[0.50367851 0.39941645 0.58448419]
  [0.84406485 0.21165801 0.05958868]
  [0.29475217 0.63539516 0.1678159 ]]

 [[0.86430836 0.23561017 0.44622467]
  [0.01822941 0.17321721 0.99307711]
  [0.03011646 0.64498851 0.41801135]]]


### 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
print(np.diag(1+np.arange(4),k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 4. Normalize a 5x5 random matrix

In [7]:
x= np.random.random((5,5))
print("Array before normalization =>\n")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("\nArray after normalization =>\n")
print(x)

Array before normalization =>

[[0.42677825 0.97525268 0.84935944 0.60097247 0.12257732]
 [0.35942801 0.10151857 0.45218013 0.04468351 0.63692339]
 [0.56656918 0.2152165  0.43428975 0.24161762 0.68087666]
 [0.66172513 0.08853255 0.23862901 0.94412157 0.80675325]
 [0.48626177 0.03389115 0.32148415 0.16009667 0.64893069]]

Array after normalization =>

[[0.41736048 1.         0.86626473 0.60240546 0.09421053]
 [0.34581491 0.07184001 0.44434467 0.01146463 0.64059579]
 [0.56585915 0.19262031 0.42533988 0.22066598 0.68728696]
 [0.66694247 0.05804507 0.21749121 0.9669297  0.82100455]
 [0.4805493  0.         0.30550749 0.134067   0.65335105]]


### 5. How to find common values between two arrays?

In [8]:
x = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)
print("x=",x,"y=",y)
print("Common values are =>\t",np.intersect1d(x,y))

x= [2 4 2 8 4 7 0 2 9 9] y= [3 7 7 1 3 7 9 0 7 2]
Common values are =>	 [0 2 7 9]


### 6.How to get the dates of yesterday, today and tomorrow?

In [9]:
day = np.datetime64('Today', 'D') 
print("Yestraday: ",day-np.timedelta64(1, 'D'))
print("Today: ",day)
print("Tomorrow: ",day+np.timedelta64(1, 'D'))

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


### 7. Consider two random array A and B, check if they are equal

In [13]:
x = np.random.randint(0,2,6)
print("First array =>\n",x)
y = np.random.randint(0,2,6)
print("Second array =>\n",y)
print("\nResult of test about the above two arrays are equal or not is",end='  ')
equal = np.array_equal(x,y)
print(equal)

First array =>
 [0 1 0 0 1 0]
Second array =>
 [1 1 1 1 1 0]

Result of test about the above two arrays are equal or not is  False


### 8.Create random vector of size 10 and replace the maximum value by 0

In [17]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("\nMaximum value replaced by 0:")
print(x)

Original array:
[1.71252669e-01 1.03275044e-03 7.82708736e-01 3.57786859e-01
 4.66382335e-01 8.52621472e-01 2.64886606e-01 4.13134367e-01
 3.15839641e-04 2.70108251e-01]

Maximum value replaced by 0:
[1.71252669e-01 1.03275044e-03 7.82708736e-01 3.57786859e-01
 4.66382335e-01 0.00000000e+00 2.64886606e-01 4.13134367e-01
 3.15839641e-04 2.70108251e-01]


### 9. How to print all the values of an array?

In [30]:
np.set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 10.Subtract the mean of each row of a matrix

In [19]:
print("Original matrix:\n")
X = np.random.rand(3, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.29137476 0.1012546  0.78318688]
 [0.47169661 0.00213364 0.46753305]
 [0.50504081 0.39852115 0.91883669]]

Subtract the mean of each row of the said matrix:

[[-0.10056399 -0.29068414  0.39124813]
 [ 0.15790885 -0.31165413  0.15374528]
 [-0.10242541 -0.20894507  0.31137047]]


### 11. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [20]:
Z = np.ones(10)
print("Before")
print(Z)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print("After\n",Z)

Before
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After
 [2. 5. 1. 3. 4. 2. 2. 6. 4. 1.]


### 12.How to get the diagonal of a dot product?

In [21]:
x = np.random.uniform(0,1,(3,3))
y = np.random.uniform(0,1,(3,3))
s=np.diag(np.dot(x,y))
print("dot product=",s)

dot product= [0.12716111 1.42360267 0.7604081 ]


### 13.How to find the most frequent value in an array?

In [28]:
x = np.random.randint(0,10,20)
print("Array =>\t",x)
print("most frequent value=",np.bincount(x).argmax())

Array =>	 [1 8 5 9 6 3 8 6 1 3 1 9 0 7 9 9 6 0 0 8]
most frequent value= 9


### 14.How to get the n largest values of an array

In [26]:
x = np.arange(10000)
np.random.shuffle(x)
n = 5
print("largest values=",x[np.argsort(x)[-n:]])

largest values= [9995 9996 9997 9998 9999]


### 15.How to create a record array from a regular array?

In [24]:
x = np.array([( 2.5, 3),
              ( 3.6, 2)])
y = np.core.records.fromarrays(x.T,names='col1, col2',formats = 'S8, f8')
print(y)

[(b'2.5', 3.) (b'3.6', 2.)]
